# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62ffb6bee49d0124e32a6cfed9999ee508bd9bb237b77cb54d53c6e80c87fed1f636fae94acdd0de27f21e18dae162580e4d042e11f2fe6d1fe218af84d376dc

test:
  secret_key_base: 76a7e8c4eb206e85177994a44a37aab88ac488bc1ad8e283826d2d3db25e06b6605d90204d5d368d54bcc86c5456cf9af7eca0e7e4d4eb78fb8c50ede88f8acd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
